### ISSUE TITLE
Can't delete an Organization that's missing a Calendar

### ISSUE THREAD

**Issue by amacnair** [amacnair/team-toolkit#13]
When attempting to delete an organization that was created without a calendar Django crashes. Traceback shows it was caused by the `instance.delete() ` call on line 58 in `organizations/views.py`.

This organization was originally created before calendars were introduced to the project so this likely won't effect users but might be a good corner case to handle?

![image](https://user-images.githubusercontent.com/6404120/32459422-9c52e9c8-c2fd-11e7-9b49-21f655e7bc3c.png)

**Comment by tfdahlin** [comment]
This is an issue with having an invalid database, and I don't think its something we can fix outside of dropping/recreating the database. Definitely not a client-side issue, more of an out-of-date code issue.
